<?php

namespace TobatBundle\Repository;

/**
 * PrefererRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrefererRepository extends \Doctrine\ORM\EntityRepository
{
}
