tobat_homepage:
    path:     /
    defaults: { _controller: TobatBundle:Default:index }

tobat_test:
    path:     /test
    defaults: { _controller: TobatBundle:Default:test }

tobat_nbVisiteursCritere:
    path:     /nbVisiteursCritere
    defaults: { _controller: TobatBundle:Default:nbVisiteursCritere }

tobat_classementBateaux:
    path:     /classementBateaux
    defaults: { _controller: TobatBundle:Default:getClassementBateaux }

tobat_enquete:
    path:    /enquete
    defaults: { _controller: TobatBundle:Default:enquete}

tobat_repartitionVisiteur:
    path:    /repartition
    defaults: { _controller: TobatBundle:Default:repartitionVisiteur }

tobat_visiteurs:
    path:    /visiteurs
    defaults: { _controller: TobatBundle:Default:visiteurs }

tobat_budget:
    path:    /budget
    defaults: { _controller: TobatBundle:Default:budget }

tobat_classement:
    path:    /classement
    defaults: { _controller: TobatBundle:Default:classement }