tobat_homepage:
    path:     /accueil
    defaults: { _controller: TobatBundle:Default:index }

tobat_enquete:
    path:    /enquete
    defaults: { _controller: TobatBundle:Default:enquete}

tobat_repartitionVisiteur:
    path:    /repartition
    defaults: { _controller: TobatBundle:Default:repartitionVisiteur }

tobat_visiteurs:
    path:    /visiteurs
    defaults: { _controller: TobatBundle:Default:visiteurs }

tobat_budget:
    path:    /budget
    defaults: { _controller: TobatBundle:Default:budget }

tobat_classement:
    path:    /classement
    defaults: { _controller: TobatBundle:Default:classement }