transnat_blog:
    resource: "@TransnatBlogBundle/Resources/config/routing.yml"
    prefix:   /

sio_blog:
    resource: "@SIOBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
