TobatBundle\Entity\Budget:
    type: entity
    table: null
    repositoryClass: TobatBundle\Repository\BudgetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        min:
            type: integer
        max:
            type: integer
    lifecycleCallbacks: {  }
