TobatBundle\Entity\Departement:
    type: entity
    table: null
    repositoryClass: TobatBundle\Repository\DepartementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
    lifecycleCallbacks: {  }
