TobatBundle\Entity\Preferer:
    type: entity
    table: null
    repositoryClass: TobatBundle\Repository\PrefererRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        modele:
            type: string
            length: 255
    lifecycleCallbacks: {  }
